version: '3.3'
services:
  web:
    build: ./taxi
    command: gunicorn taxi.wsgi:application --bind 0.0.0.0:8000
    volumes:
        - static_volume:/app/staticfiles
        - ./fixtures:/tmp/fixtures
    restart: always
    env_file:
        - ./.env.prod
    depends_on:
        - db
    
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/staticfiles
    ports:
      - 83:80
    depends_on:
      - web
    restart: always

  db:
    image: postgres:15.1
    volumes:
      - db:/var/lib/postgresql/data
      - ./init_readonly_user.sh:/docker-entrypoint-initdb.d/init_readonly_user.sh      
    ports:
        - 5432:5432
    restart: always
    env_file:
      - ./.env.prod
    environment:
      - POSTGRES_PASSWORD=postgres


volumes:    
    db:
      driver: local
    static_volume: