#!/bin/sh

set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "postgres" <<-EOSQL
    CREATE USER "$READONLY_USERNAME" WITH PASSWORD '$READONLY_PASSWORD';
    ALTER ROLE "$READONLY_USERNAME" SET client_encoding TO 'utf8';
    ALTER ROLE "$READONLY_USERNAME" SET default_transaction_isolation TO 'read committed';
    ALTER ROLE "$READONLY_USERNAME" SET timezone TO 'UTC';
    GRANT USAGE ON SCHEMA public TO "$READONLY_USERNAME";
    GRANT SELECT ON ALL TABLES IN SCHEMA public TO "$READONLY_USERNAME";
    ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO "$READONLY_USERNAME";
EOSQL